# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 17:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster_name', models.CharField(max_length=200)),
                ('poster_avatar', models.CharField(max_length=200)),
                ('poster_degree', models.CharField(max_length=200)),
                ('post_title', models.TextField()),
                ('post_content', models.TextField()),
                ('votes', models.IntegerField()),
                ('answers', models.IntegerField()),
                ('views', models.IntegerField()),
                ('vote_type', models.IntegerField()),
                ('bookmarked', models.BooleanField()),
                ('is_read', models.BooleanField()),
                ('is_mine', models.BooleanField()),
                ('is_published', models.BooleanField()),
                ('is_locked', models.BooleanField()),
                ('is_question', models.BooleanField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('avatar', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('profession', models.CharField(max_length=200)),
                ('degree', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('activation_status', models.IntegerField()),
                ('reg_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='poster_mysql_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.User'),
        ),
        migrations.AddField(
            model_name='post',
            name='question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.Post'),
        ),
    ]
