# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-18 15:32
from __future__ import unicode_literals

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20170117_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_content',
            field=froala_editor.fields.FroalaField(),
        ),
    ]
