# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-18 15:37
from __future__ import unicode_literals

from django.db import migrations, models
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_auto_20170118_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=froala_editor.fields.FroalaField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='post_content',
            field=models.TextField(),
        ),
    ]
