# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_auto_20170106_2059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='poster_mysql_id',
            new_name='poster',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='question_id',
            new_name='question',
        ),
        migrations.RemoveField(
            model_name='post',
            name='answers',
        ),
        migrations.RemoveField(
            model_name='post',
            name='bookmarked',
        ),
        migrations.RemoveField(
            model_name='post',
            name='is_mine',
        ),
        migrations.RemoveField(
            model_name='post',
            name='is_read',
        ),
        migrations.RemoveField(
            model_name='post',
            name='poster_avatar',
        ),
        migrations.RemoveField(
            model_name='post',
            name='poster_degree',
        ),
        migrations.RemoveField(
            model_name='post',
            name='poster_name',
        ),
        migrations.RemoveField(
            model_name='post',
            name='vote_type',
        ),
        migrations.AddField(
            model_name='post',
            name='is_deleted',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='views',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='votes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
