# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-18 16:50
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_auto_20170118_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
