# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-29 05:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_authenticate'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date_modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
